#!/bin/bash

check() {
  if [ ! -f $SERVICE_INGRESS_L2TP_CONFIG_ROUTER ]; then
    log::error "[ingress] please config ingress router in $SERVICE_INGRESS_L2TP_CONFIG_ROUTER"
    exit 1
  fi

  config::check_or_set SERVICE_INGRESS_L2TP_DOMAIN text $SERVICE_CONFIG "请输入服务域名:"
  config::check_or_set SERVICE_INGRESS_L2TP_VPN_SERVER text $SERVICE_CONFIG "请输入 VPN 服务器地址:"
  config::check_or_set SERVICE_INGRESS_L2TP_VPN_USERNAME text $SERVICE_CONFIG "请输入 VPN 用户名:"
  config::check_or_set SERVICE_INGRESS_L2TP_VPN_PASSWORD text $SERVICE_CONFIG "请输入 VPN 密码:"
  config::check_or_set SERVICE_INGRESS_L2TP_VPN_IPSEC_PSK text $SERVICE_CONFIG "请输入 VPN 共享密钥:"

  # load again
  config::load_file $SERVICE_CONFIG
}

check $@
